name: Deploy Golang Application with Serverless

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace string ACCESS_KEY in .env file
        uses: MathieuSoysal/replace-string-in-file@v1.0.0
        with:
          file: .env
          old-string: ACCESS_KEY
          new-string: ${{ secrets.ACCESS_KEY_ID }}

      - name: Replace string SECRET_KEY in .env file
        uses: MathieuSoysal/replace-string-in-file@v1.0.0
        with:
          file: .env
          old-string: SECRET_KEY
          new-string: ${{ secrets.AWS_SECRET_ACCESS_KEY_SCAPED }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.19'

      - name: Build Go executable
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bin/main main.go

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy with Serverless Framework
        run: |
          npm install -g serverless
          serverless deploy
